---
title: "Data Visualization tutorial"
author: "by Dominic White"
tutorial:
  version: 1.2
output:
  learnr::tutorial:
    progressive: true
    allow_skip: true
runtime: shiny_prerendered
---

<style>
p.comment {
background-color: #EDBB99;
padding: 10px;
border: 1px solid black;
font-style: italic;
}
</style>

<style>
p.comment1 {
background-color: #A2D9CE;
padding: 10px;
border: 1px solid black;
}
</style>

<style>
p.comment2 {
background-color: #EDBB99; 
padding: 10px;
border: 1px solid black;
}
</style>

<style>
p.comment3 {
background-color: #FDFEFE; 
padding: 10px;
border: 1px solid black;
}
</style>


```{r setup, include=FALSE, context="setup"}
library(tidyverse)
library(learnr)
library(gradethis)
library(checkr)
library(sortable)
library(diffobj)
library(flair)
library(listviewer)

knitr::opts_chunk$set(echo = FALSE)
tutorial_options(exercise.checker = grade_learnr)
tutorial_options(exercise.startover = TRUE)
tutorial_options(exercise.completion = FALSE)

new_recorder <- function(tutorial_id, tutorial_version, user_id, event, data) {
    #cat(tutorial_id, " (", tutorial_version, "): ", user_id, ", ", event, ", ", "\n", sep = "")
  cat(tutorial_id, " (", tutorial_version, "): ", user_id , "\n", sep = "")
  cat("event: ", event, "\n", sep = "")
}

options(tutorial.event_recorder = new_recorder)
```

## Welcome

This tutorial will introduce you to creating graphs in R.

## Visualization principles

This video will introduce you to the importance of visualization in data science, and how it can be used effectively (or ineffectively).

<iframe width="560" height="315" src="https://www.youtube.com/embed/tHEVRahx0WE?rel=0" frameborder="0" allowfullscreen></iframe>

Slides: [PDF](https://drive.google.com/file/d/1VK_vXEHBK5U35rfgetwon07A7YLpaj_H/edit)


## Creating Basic Graphs

This video will teach you how to create simple graphs in R.

<iframe width="560" height="315" src="https://www.youtube.com/embed/8JoPQZq327w?rel=0" frameborder="0" allowfullscreen></iframe>

## Interpreting Scatter Plots

This video will teach you about the patterns that can be described from scatter plots.

<iframe width="560" height="315" src="https://www.youtube.com/embed/ZhXwfkUk8gQ?rel=0" frameborder="0" allowfullscreen></iframe>

<!-- Slides: [PDF](https://drive.google.com/file/d/1KiY4qavGUf3gMQF5rg1cR5HzmaI9i0dQ/edit) -->

## Graphs of One Variable

Scatter plots show the co-variation between two variables. But often we want to examination in just a single variable.

This video will show you how to create histograms to visualize continuous variables and bar graphs to visualize categorical variables.

<iframe width="560" height="315" src="https://www.youtube.com/embed/PJXEauOPuEA?rel=0" frameborder="0" allowfullscreen></iframe>

## Interpreting Histograms

This video will teach you how to describe the shape of histograms.

<iframe width="560" height="315" src="https://www.youtube.com/embed/3Bhke58QC4g?rel=0" frameborder="0" allowfullscreen></iframe>

